# silhouet_config.py

# Define your comprehensive list of personality keys.
# This list must be identical and ordered consistently across all services
# that refer to personality scores.
PERSONALITY_KEYS = [
    "intellectual_honesty",
    "courage",
    "nobility",
    "self_respect",
    "empathy",
    "aggression",
    "resentment",
    "idealism",
    "cynicism",
    "loneliness",
    "creativity",
    "frustration",
    "conformity_pressure",
    "tribal_affiliation",
    "curiosity",
    "innovation_optimism",
    "self_worth",
    "willingness_conspiracy_theories",
    "emotional_state_anxiety",
    "emotional_state_sadness",
    "emotional_state_anger",
    "attachment_needs",
    "self_loathing",
    "pride",
    "relationship_satisfaction",
    "desire_for_connection",
    "ambition_motivation",
    "gratitude",
    "entitlement",
    "fear_of_judgment",
    "confidence_in_future_self",
    "shame",
    "guilt",
    "trust_in_institutions",
    "perception_of_justice",
    "moral_alignment_with_society",
    "dissatisfaction_with_culture_media",
    "concern_over_decline_collapse",
    "political_engagement_level",
    "faith_in_democracy",
    "sense_of_alienation",
    "systemic_paranoia",
    "preference_for_strong_leadership_vs_consensus",
    "libertarianism_vs_collectivism",
    "tolerance_for_authority",
    "openness_to_change_reform",
    "compliance_sentiment",
    "views_on_taxation",
    "polarization_intensity",
    "willingness_to_protest_or_comply",
    "brand_loyalty",
    "frustration_with_products",
    "openness_to_alternatives",
    "cost_sensitivity",
    "trust_in_advertising",
    "expectations_from_businesses",
    "belief_in_capitalism",
    "personal_financial_satisfaction"
]

# Aggregation frequencies in hours (can be loaded from environment variables)
AGGREGATION_FREQUENCIES = {
    "pincode": 1,
    "district": 2,
    "state": 4,
    "country": 6,
    "world": 24,
}

PERSONALITY_LABEL_MAP = {
    "intellectual_honesty": ("This text demonstrates intellectual honesty.", "This text demonstrates intellectual dishonesty."),
    "courage": ("This text expresses courage.", "This text expresses fear or cowardice."),
    "nobility": ("This text expresses noble sentiments.", "This text expresses ignoble sentiments."),
    "self_respect": ("This text shows high self-respect.", "This text shows low self-respect."),
    "empathy": ("This text conveys empathy towards others.", "This text conveys a lack of empathy towards others."),
    "aggression": ("This text displays aggression.", "This text displays peacefulness."),
    "resentment": ("This text expresses resentment.", "This text expresses contentment."),
    "idealism": ("This text expresses idealism.", "This text expresses pragmatism or realism."),
    "cynicism": ("This text expresses cynicism.", "This text expresses optimism or belief."),
    "loneliness": ("This text conveys loneliness.", "This text conveys a sense of connection."),
    "creativity": ("This text demonstrates creativity.", "This text lacks creativity or is conventional."),
    "frustration": ("This text expresses frustration.", "This text expresses calmness or satisfaction."),
    "conformity_pressure": ("This text indicates pressure to conform.", "This text indicates individuality or non-conformity."),
    "tribal_affiliation": ("This text shows strong tribal or group affiliation.", "This text shows individualism or universalism."),
    "curiosity": ("This text expresses curiosity.", "This text expresses indifference or lack of interest."),
    "innovation_optimism": ("This text expresses optimism about innovation.", "This text expresses pessimism about innovation."),
    "self_worth": ("This text conveys high self-worth.", "This text conveys low self-worth."),
    "willingness_conspiracy_theories": ("This text shows a willingness to believe conspiracy theories.", "This text shows skepticism towards conspiracy theories."),
    "emotional_state_anxiety": ("This text reflects high anxiety.", "This text reflects calmness."),
    "emotional_state_sadness": ("This text expresses sadness.", "This text expresses happiness."),
    "emotional_state_anger": ("This text expresses anger.", "This text expresses tranquility."),
    "attachment_needs": ("This text expresses strong attachment needs.", "This text expresses independence."),
    "self_loathing": ("This text expresses self-loathing.", "This text expresses self-acceptance."),
    "pride": ("This text expresses pride.", "This text expresses humility or shame."),
    "relationship_satisfaction": ("This text indicates relationship satisfaction.", "This text indicates relationship dissatisfaction."),
    "desire_for_connection": ("This text expresses a desire for connection.", "This text expresses a desire for solitude."),
    "ambition_motivation": ("This text conveys high ambition or motivation.", "This text conveys a lack of ambition or motivation."),
    "gratitude": ("This text expresses gratitude.", "This text expresses ungratefulness."),
    "entitlement": ("This text expresses a sense of entitlement.", "This text expresses humility or gratitude."),
    "fear_of_judgment": ("This text expresses fear of judgment.", "This text expresses confidence or indifference to judgment."),
    "confidence_in_future_self": ("This text shows confidence in future self.", "This text shows doubt in future self."),
    "shame": ("This text expresses shame.", "This text expresses pride or confidence."),
    "guilt": ("This text expresses guilt.", "This text expresses innocence or blamelessness."),
    "trust_in_institutions": ("This text expresses trust in institutions.", "This text expresses distrust in institutions."),
    "perception_of_justice": ("This text perceives justice to be present.", "This text perceives injustice to be present."),
    "moral_alignment_with_society": ("This text shows moral alignment with society.", "This text shows moral misalignment with society."),
    "dissatisfaction_with_culture_media": ("This text expresses dissatisfaction with culture or media.", "This text expresses satisfaction with culture or media."),
    "concern_over_decline_collapse": ("This text expresses concern over decline or collapse.", "This text expresses optimism about the future."),
    "political_engagement_level": ("This text shows high political engagement.", "This text shows low political engagement."),
    "faith_in_democracy": ("This text expresses faith in democracy.", "This text expresses a lack of faith in democracy."),
    "sense_of_alienation": ("This text expresses a sense of alienation.", "This text expresses a sense of belonging."),
    "systemic_paranoia": ("This text expresses systemic paranoia.", "This text expresses trust in systems."),
    "preference_for_strong_leadership_vs_consensus": ("This text prefers strong leadership.", "This text prefers consensus-based leadership."),
    "libertarianism_vs_collectivism": ("This text expresses libertarian views.", "This text expresses collectivist views."),
    "tolerance_for_authority": ("This text expresses tolerance for authority.", "This text expresses defiance towards authority."),
    "openness_to_change_reform": ("This text expresses openness to change or reform.", "This text expresses resistance to change or reform."),
    "compliance_sentiment": ("This text expresses compliance.", "This text expresses non-compliance."),
    "views_on_taxation": ("This text expresses positive views on taxation.", "This text expresses negative views on taxation."),
    "polarization_intensity": ("This text shows high polarization.", "This text shows low polarization."),
    "willingness_to_protest_or_comply": ("This text expresses willingness to protest.", "This text expresses willingness to comply."),
    "brand_loyalty": ("This text expresses brand loyalty.", "This text expresses brand disloyalty."),
    "frustration_with_products": ("This text expresses frustration with products.", "This text expresses satisfaction with products."),
    "openness_to_alternatives": ("This text expresses openness to alternatives.", "This text expresses resistance to alternatives."),
    "cost_sensitivity": ("This text shows high cost sensitivity.", "This text shows low cost sensitivity."),
    "trust_in_advertising": ("This text expresses trust in advertising.", "This text expresses distrust in advertising."),
    "expectations_from_businesses": ("This text expresses high expectations from businesses.", "This text expresses low expectations from businesses."),
    "belief_in_capitalism": ("This text expresses belief in capitalism.", "This text expresses disbelief in capitalism."),
    "personal_financial_satisfaction": ("This text expresses personal financial satisfaction.", "This text expresses personal financial dissatisfaction.")
}
