// frontend/src/config.ts

export const API_BASE_URL = process.env.REACT_APP_API_BASE_URL || 'http://localhost:8000';

export const AD_FEED_ENDPOINT = '/messages/next';
export const INSIGHT_FEED_ENDPOINT = '/messages/insights';

export const PERSONALITY_KEYS = [
    "intellectual_honesty",
    "courage",
    "nobility",
    "self_respect",
    "empathy",
    "aggression",
    "resentment",
    "idealism",
    "cynicism",
    "loneliness",
    "creativity",
    "frustration",
    "conformity_pressure",
    "tribal_affiliation",
    "curiosity",
    "innovation_optimism",
    "self_worth",
    "willingness_conspiracy_theories",
    "emotional_state_anxiety",
    "emotional_state_sadness",
    "emotional_state_anger",
    "attachment_needs",
    "self_loathing",
    "pride",
    "relationship_satisfaction",
    "desire_for_connection",
    "ambition_motivation",
    "gratitude",
    "entitlement",
    "fear_of_judgment",
    "confidence_in_future_self",
    "shame",
    "guilt",
    "trust_in_institutions",
    "perception_of_justice",
    "moral_alignment_with_society",
    "dissatisfaction_with_culture_media",
    "concern_over_decline_collapse",
    "political_engagement_level",
    "faith_in_democracy",
    "sense_of_alienation",
    "systemic_paranoia",
    "preference_for_strong_leadership_vs_consensus",
    "libertarianism_vs_collectivism",
    "tolerance_for_authority",
    "openness_to_change_reform",
    "compliance_sentiment",
    "views_on_taxation",
    "polarization_intensity",
    "willingness_to_protest_or_comply",
    "brand_loyalty",
    "frustration_with_products",
    "openness_to_alternatives",
    "cost_sensitivity",
    "trust_in_advertising",
    "expectations_from_businesses",
    "belief_in_capitalism",
    "personal_financial_satisfaction"
];
